defaults:
  - machine: 2080ti

# Directory Config
DATA_PATH: /home/yani/hugo/kaggle/kaggle_bengali_recognition/data/processed/size_224_v3
save_dir: /home/yani/hugo/kaggle/kaggle_bengali_recognition/models/head3fc

wandb_log: True
exp_name: base
project: my-project

# Custom config
swa: True

# ONLY CROSS_ENTROPY LOSS SUPPORT WEIGHTED CLASS LOSS NOW
is_weighted_class_loss: True

# prob. of using ["cross_entropy", "ohem"] loss
train_loss_prob_2: [0.5, 0.5]
# prob. of using extra img augmentation ["mixup", "cutmix", "none"]
extra_augmentation_prob: [0.5, 0.5, 0.0]
# for mixup/cutmix only
mixup_alpha: 0.4
cutmix_alpha: 0.4
# for ohem only
ohem_rate: 0.7
# weighted loss of [root, vowel, consonant]
head_weights: [0.5, 0.25, 0.25]

head: Head_3fc
batch_scheduler_func: optim.lr_scheduler.CyclicLR
batch_scheduler_func_para: {"base_lr": 0.001, "max_lr":0.006, "step_size_up":314, "cycle_momentum": False}
optimizer: optim.AdamW
optimizer_parameter: {"lr": 0.003}
model_arch: se_resnext101_pretrained
model_parameter: {}
error_plateau_scheduler_func: None
error_plateau_scheduler_func_para: {}
epoch_scheduler_func: None
epoch_scheduler_func_para: {}
data_transforms:
  rotate: 15
  scale: [1.0, 1.1]
  p_affine: 0.75
  shear: 0

# Base Config
random_seed: 2020
num_workers: 2
pin_memory: True
n_splits: 5
n_epoch: 80
