defaults:
  - machine: 2080ti

# Directory Config
DATA_PATH: /home/hugo/Desktop/kaggle/kaggle_bengali_recognition/data/processed/size_128
save_dir: /home/hugo/Desktop/kaggle/kaggle_bengali_recognition/models/testing

wandb_log: True
exp_name: base
project: my-project

# Custom config
swa: False

# ONLY CROSS_ENTROPY LOSS SUPPORT WEIGHTED CLASS LOSS NOW
is_weighted_class_loss: False

# prob. of using ["cross_entropy", "ohem"] loss
train_loss_prob_2: [1.0, 0.0]
# prob. of using extra img augmentation ["mixup", "cutmix", "none"]
extra_augmentation_prob: [1.0, 0.0, 0.0]
# for mixup/cutmix only
mixup_alpha: 0.4
cutmix_alpha: 1
# for ohem only
ohem_rate: 0.7
# weighted loss of [root, vowel, consonant]
head_weights: [0.5, 0.25, 0.25]

head: Head_1fc
optimizer: optim.Adam
optimizer_parameter: {}
model_arch: se_resnext50
model_parameter: {}
error_plateau_scheduler_func: None
error_plateau_scheduler_func_para: {}
epoch_scheduler_func: None
epoch_scheduler_func_para: {}
data_transforms:
  rotate: 10
  scale: [1.0, 1.1]
  p_affine: 0.75
  shear: 0

# Base Config
random_seed: 2020
num_workers: 2
pin_memory: True
n_splits: 5
n_epoch: 120
